# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: wendywalk_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wendywalk_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wendywalk_prod
  pool: 5
  timeout: 5000
